"""empty message

Revision ID: 640bfa890694
Revises: f2377904af3a
Create Date: 2024-12-03 12:59:39.097841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '640bfa890694'
down_revision = 'f2377904af3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('author', sa.Text(), nullable=False),
    sa.Column('creator', sa.Text(), nullable=False),
    sa.Column('creationDate', sa.Text(), nullable=False),
    sa.Column('uploadDate', sa.Text(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    # ### end Alembic commands ###
